### ISSUE TITLE
Not working with Sketch 79.1 (133344) / Sonoma

### ISSUE THREAD

**Issue by alexanderhupfer** [oodesign/mesh-gradients#7]
Hi, I was able to install the plugin, but nothing happens when I click the menu item.

**Comment by oodesign** [comment]
Hi @alexanderhupfer ,

Which version of Mesh gradients are you using?
Just in case, you may always find the latest version [here on Github](https://github.com/oodesign/mesh-gradients/releases).

**Comment by alexanderhupfer** [comment]
I used the latest from Github. Is there a debug output/logs I should look into?

**Comment by oodesign** [comment]
Hi!

We are able to reproduce the issue with Sketch 79.1 and Sonoma.

The good news is that we can see what is causing the issue (an issue due to both [Sketch API](https://github.com/sketch-hq/SketchAPI/issues/909) and  [skpm](https://github.com/skpm/sketch-module-web-view/issues/183)). The bad news is that I'm afraid there is not much we can do about it... 🙈.

Seems that the only solution would be upgrading to a newer version of Sketch (93+).

That said, if you acquired a license for Mesh gradients and you can't use it, please reach out via [mail](mailto:support@oodesign.me) with your license key or the email you used to complete the purchase, and we'd be happy to refund your purchase(*).

(*) Paypal payments can't be refund after 6 months. If that may be your case, we'd need to find another alternative 😊 .

**Comment by alexanderhupfer** [comment]
Thank you, after upgrading everything works :)

**Comment by oodesign** [comment]
Glad that it's working fine for you now! 😊
